[project]
name = "agent-1-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.0.5",
    "langchain-openai>=1.0.2",
    "langchain-tavily>=0.2.13",
]
